// This file is automatically generated by TIKNAS framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Tiknas.Application.Dtos;
using Tiknas.Http.Client;
using Tiknas.Http.Modeling;
using Tiknas.DependencyInjection;
using Tiknas.Http.Client.ClientProxying;
using Tiknas.AspNetCore.Mvc.ApplicationConfigurations;

// ReSharper disable once CheckNamespace
namespace Tiknas.AspNetCore.Mvc.ApplicationConfigurations.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(ITiknasApplicationLocalizationAppService), typeof(TiknasApplicationLocalizationClientProxy))]
public partial class TiknasApplicationLocalizationClientProxy : ClientProxyBase<ITiknasApplicationLocalizationAppService>, ITiknasApplicationLocalizationAppService
{
    public virtual async Task<ApplicationLocalizationDto> GetAsync(ApplicationLocalizationRequestDto input)
    {
        return await RequestAsync<ApplicationLocalizationDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(ApplicationLocalizationRequestDto), input }
        });
    }
}
