// This file is automatically generated by TIKNAS framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Tiknas.Application.Dtos;
using Tiknas.Http.Client;
using Tiknas.Http.Modeling;
using Tiknas.DependencyInjection;
using Tiknas.Http.Client.ClientProxying;
using Tiknas.AspNetCore.Mvc.MultiTenancy;

// ReSharper disable once CheckNamespace
namespace Pages.Tiknas.MultiTenancy.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(ITiknasTenantAppService), typeof(TiknasTenantClientProxy))]
public partial class TiknasTenantClientProxy : ClientProxyBase<ITiknasTenantAppService>, ITiknasTenantAppService
{
    public virtual async Task<FindTenantResultDto> FindTenantByNameAsync(string name)
    {
        return await RequestAsync<FindTenantResultDto>(nameof(FindTenantByNameAsync), new ClientProxyRequestTypeValue
        {
            { typeof(string), name }
        });
    }

    public virtual async Task<FindTenantResultDto> FindTenantByIdAsync(Guid id)
    {
        return await RequestAsync<FindTenantResultDto>(nameof(FindTenantByIdAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }
}
