// This file is automatically generated by TIKNAS framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Tiknas.Application.Dtos;
using Tiknas.Http.Client;
using Tiknas.Http.Modeling;
using Tiknas.DependencyInjection;
using Tiknas.Http.Client.ClientProxying;
using Tiknas.AspNetCore.Mvc.ApplicationConfigurations;

// ReSharper disable once CheckNamespace
namespace Tiknas.AspNetCore.Mvc.ApplicationConfigurations.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(ITiknasApplicationConfigurationAppService), typeof(TiknasApplicationConfigurationClientProxy))]
public partial class TiknasApplicationConfigurationClientProxy : ClientProxyBase<ITiknasApplicationConfigurationAppService>, ITiknasApplicationConfigurationAppService
{
    public virtual async Task<ApplicationConfigurationDto> GetAsync(ApplicationConfigurationRequestOptions options)
    {
        return await RequestAsync<ApplicationConfigurationDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(ApplicationConfigurationRequestOptions), options }
        });
    }
}
